# Generated by Django 5.2.7 on 2026-04-19 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название акции')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Слаг')),
                ('teaser', models.TextField(blank=True, verbose_name='Кратко для главной')),
                ('description', models.TextField(verbose_name='Полное описание / условия')),
                ('bonus_summary', models.CharField(blank=True, help_text='Например: до 2000 ₽ за отзыв', max_length=200, verbose_name='Размер бонуса / приз')),
                ('conditions', models.TextField(blank=True, verbose_name='Условия участия')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('how_to_get', models.TextField(blank=True, verbose_name='Как получить бонус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции и бонусы',
                'ordering': ['ordering', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PromotionReviewSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('review_url', models.URLField(verbose_name='Ссылка на отзыв')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_submissions', to='promotions.promotion', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Заявка на бонус (ссылка на отзыв)',
                'verbose_name_plural': 'Заявки на бонус',
                'ordering': ['-created_at'],
            },
        ),
    ]
