# Generated by Django 5.2.7 on 2026-02-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий администратора'),
        ),
    ]
