# Generated by Django 5.2.7 on 2026-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactrequest_admin_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='Для быстрой заявки с главной', max_length=200, verbose_name='Тип авто / услуга'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
    ]
