# Generated by Django 5.2.7 on 2025-11-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='Название сайта')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('working_hours', models.CharField(max_length=255, verbose_name='Часы работы')),
                ('social_media_links', models.JSONField(blank=True, null=True, verbose_name='Ссылки на соцсети')),
                ('meta_tags', models.TextField(blank=True, verbose_name='Мета-теги (SEO)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
