# Generated by Django 5.2.7 on 2026-02-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_completed', models.PositiveIntegerField(default=0, verbose_name='Количество выполненных проектов')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Годы опыта работы')),
                ('satisfied_clients_percentage', models.PositiveIntegerField(default=0, verbose_name='Процент довольных клиентов')),
                ('specialists_count', models.PositiveIntegerField(default=0, verbose_name='Количество специалистов')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='meta_tags',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='additional_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='additional_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_description',
            field=models.TextField(default='Профессиональное переоборудование грузовиков, установка КМУ, доработка фургонов в Омске и области.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_title',
            field=models.CharField(default='Переделка55 - Переоборудование спецтехники', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='keywords',
            field=models.CharField(default='переоборудование, спецтехника, кму, омск', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_email',
            field=models.EmailField(default='info@peredelka55.ru', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_phone',
            field=models.CharField(default='+7 (XXX) XXX-XX-XX', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og_images/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_social_icons',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vk_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='г. Омск, ул. Примерная, д. 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Peredelka55', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Peredelka55', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='working_hours',
            field=models.CharField(default='Пн-Пт: 9:00-18:00', max_length=100),
        ),
    ]
