# Generated by Django 5.2.7 on 2026-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_statistic_remove_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='г. Нижний Новгород, ул. Юлиуса Фучика, д. 60, корп. 5', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_meta_description',
            field=models.TextField(default='Полный цикл переоборудования коммерческого транспорта: еврофургоны, эвакуаторные платформы, КМУ, цистерны, удлинение рам. Работаем с 2011 года.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='main_email',
            field=models.EmailField(default='avtorekord-nn@mail.ru', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='main_phone',
            field=models.CharField(default='8 (800) 222-97-92', max_length=30),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='projects_completed',
            field=models.PositiveIntegerField(default=7000, help_text='По ТЗ: более 7000 проектов по России и СНГ', verbose_name='Количество выполненных проектов'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='satisfied_clients_percentage',
            field=models.PositiveIntegerField(default=98, verbose_name='Процент довольных клиентов'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='specialists_count',
            field=models.PositiveIntegerField(default=25, verbose_name='Количество специалистов'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=15, help_text='С 2011 года', verbose_name='Годы опыта работы'),
        ),
    ]
