# Generated by Django 5.2.7 on 2025-11-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='guarantee',
            field=models.TextField(blank=True, verbose_name='Гарантия'),
        ),
        migrations.AddField(
            model_name='service',
            name='specialist_visit',
            field=models.BooleanField(default=False, verbose_name='Возможен выезд специалиста'),
        ),
        migrations.AddField(
            model_name='service',
            name='terms',
            field=models.TextField(blank=True, verbose_name='Сроки выполнения'),
        ),
        migrations.AddField(
            model_name='service',
            name='work_process',
            field=models.TextField(blank=True, verbose_name='Процесс работы'),
        ),
    ]
