# Generated by Django 5.2.7 on 2026-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service_type',
            field=models.CharField(choices=[('other', 'Другое'), ('frame_extension', 'Удлинение рамы'), ('euro_van', 'Еврофургон'), ('evacuator', 'Эвакуатор / платформа'), ('kmu', 'КМУ'), ('vacuum', 'Вакуумная цистерна'), ('gbo', 'ГБО / навесное'), ('complex', 'Комплексное переоборудование')], default='other', max_length=32, verbose_name='Тип услуги'),
        ),
    ]
