# Generated by Django 5.2.7 on 2025-11-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Категория техники')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('before_image', models.ImageField(upload_to='portfolio/before/', verbose_name='Фото до')),
                ('after_image', models.ImageField(upload_to='portfolio/after/', verbose_name='Фото после')),
                ('completion_date', models.DateField(verbose_name='Дата завершения')),
                ('services_used', models.ManyToManyField(blank=True, to='services.service', verbose_name='Использованные услуги')),
            ],
            options={
                'verbose_name': 'Элемент портфолио',
                'verbose_name_plural': 'Портфолио',
                'ordering': ['-completion_date'],
            },
        ),
    ]
