# Generated by Django 5.2.7 on 2025-11-30 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория портфолио',
                'verbose_name_plural': 'Категории портфолио',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['completion_date'], 'verbose_name': 'Элемент портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='portfolio.portfoliocategory', verbose_name='Категория техники'),
        ),
    ]
