# Generated by Django 5.2.7 on 2025-11-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliocategory_alter_portfolioitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
