# Generated by Django 5.2.7 on 2026-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolioitem_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='chassis_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тип шасси'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='equipment_summary',
            field=models.TextField(blank=True, verbose_name='Установленное оборудование'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='price_display',
            field=models.CharField(blank=True, help_text='Например: от 450 000 ₽ или «индивидуальный расчёт»', max_length=120, verbose_name='Цена / диапазон'),
        ),
    ]
